const ADD_TODO = 'ADD_TODO';
const SET_TODOS = 'SET_TODOS';
const INITIAL_TODOS ='INITIAL_TODOS';
const DELETE_TODOS = 'DELETE_TODOS';
const DELETE_TODO = 'DELETE_TODO';
const EDIT_TODO = 'EDIT_TODO';
const COMPLETE_TODO = 'COMPLETE_TODO';
const COMPLETE_ALL_TODOS = 'COMPLETE_ALL_TODOS';
const SET_FILTER = 'SET_FILTER';

export const names = {
    ADD_TODO, SET_TODOS, INITIAL_TODOS, DELETE_TODOS,
    DELETE_TODO, COMPLETE_TODO, COMPLETE_ALL_TODOS, SET_FILTER, EDIT_TODO
};